### ISSUE TITLE
libjudy doesn't compile in build directory

### ISSUE THREAD

**Issue by mboman** [darconeous/miredo-osx#2]
When I try to "make libjudy" I get the following error:

libtool: link: ar cru .libs/libJudyMalloc.a  JudyMalloc.o
libtool: link: ranlib .libs/libJudyMalloc.a
libtool: link: ( cd ".libs" && rm -f "libJudyMalloc.la" && ln -s "../libJudyMalloc.la" "libJudyMalloc.la" )
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for`install-data-am'.
Making install in JudyL
cp -f ../JudyCommon/JudyCascade.c           JudyLCascade.c
cp: ../JudyCommon/JudyCascade.c: No such file or directory
make[3]: **\* [JudyLCascade.c] Error 1
make[2]: **\* [install-recursive] Error 1
make[1]: **\* [install-recursive] Error 1
make: **\* [/Users/michael/Dropbox/Src/miredo-osx/build/judy_out_x86/lib/libJudy.a] Error 2

It compiles nicely on its own. After some checking I noticed that JudyCascade.c is not being copied to build/judy_build_x86/src/JudyCommon/

**Comment by darconeous** [comment]
I'm no longer working on this project. Hopefully someone else can (or has?) forked it and continue development.
