### ISSUE TITLE
[README.txt] Website for tuntaposx changed

### ISSUE THREAD

**Issue by pklaus** [darconeous/miredo-osx#3]
Hi! In The README.md, the website for the tuntaposx project it is given as http://www-user.rhrk.uni-kl.de/~nissler/tuntap/
In the meantime, however, the project was given a new site which can be found on <http://www-user.rhrk.uni-kl.de/~nissler/tuntap/ http://tuntaposx.sourceforge.net/>.

The change was too small to fork the whole miredo-osx ;)

**Comment by darconeous** [comment]
I'm no longer working on this project. Hopefully someone else can (or has?) forked it and continue development.
